name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: python_user
          POSTGRES_PASSWORD: 1234567890
          POSTGRES_DB: python_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
          pip install psycopg2-binary pytest celery Django django-environ django_celery_results psycopg2 pytest pytest-django pytest-mock redis
      - name: Create Database
        run: |
          python manage.py migrate
      - name: Run Tests
        env:
          DATABASE_URL: postgresql://python_user:1234567890@localhost:5432/python_db
        run: |
          python manage.py test
